insert into TBL_PRODUCT (NAME,PRICE,DESCRIPTION,CATEGORY,BRAND) VALUES('IPhone 14',140000,'Black Color,8 128 Gb ','Mobile','Apple');
insert into TBL_PRODUCT (NAME,PRICE,DESCRIPTION,CATEGORY,BRAND) VALUES('IPhone 13',100000,'white Color,8 128 Gb ','Mobile','Apple');
insert into TBL_PRODUCT (NAME,PRICE,DESCRIPTION,CATEGORY,BRAND) VALUES('Washing Machine',40000,'Black Color,10 Diff Mode','Washing Machine','LG');
insert into TBL_PRODUCT (NAME,PRICE,DESCRIPTION,CATEGORY,BRAND) VALUES('Sony Bravia',190000,'HD Panel,Android','TV','Sony');
insert into TBL_PRODUCT (NAME,PRICE,DESCRIPTION,CATEGORY,BRAND) VALUES('Samsung s23 ultra',240000,'Black Color,12 256 Gb ','Mobile','Samsung');

insert into TBL_USER (user_name,EMAIL,PASSWORD,PHONE_NUMBER) VALUES('Keval','keval@gmail.com','keval','884776993');
insert into TBL_USER (user_name,EMAIL,PASSWORD,PHONE_NUMBER) VALUES('Parth','parth@gmail.com','ParthWate','884776988');
insert into TBL_USER (user_name,EMAIL,PASSWORD,PHONE_NUMBER) VALUES('Rohit','rohit@gmail.com','RohitMandale','7054638292');
insert into TBL_USER (user_name,EMAIL,PASSWORD,PHONE_NUMBER) VALUES('Riya','riya@gmail.com','Riya123','8847909093');
insert into TBL_USER (user_name,EMAIL,PASSWORD,PHONE_NUMBER) VALUES('Bhavana','bhumi@gmail.com','bhass','8378011836');

insert into TBL_ADDRESS (NAME,LANDMARK,STATE,ZIP_CODE,PHONE_NUMBER,USER_ID) VALUES('Brahman Sabha Colony','near hanuman madir,Paratwada','Maharastra','444805','884776993',1);
insert into TBL_ADDRESS (NAME,LANDMARK,STATE,ZIP_CODE,PHONE_NUMBER,USER_ID) VALUES('Mil Colony','Achalpur','Maharastra','444806','7058693391',2);
insert into TBL_ADDRESS (NAME,LANDMARK,STATE,ZIP_CODE,PHONE_NUMBER,USER_ID) VALUES('Friend Colony','Kandali','Maharastra','444806','705869323',3);
insert into TBL_ADDRESS (NAME,LANDMARK,STATE,ZIP_CODE,PHONE_NUMBER,USER_ID) VALUES('Ekvira VOlony','Near Ambadevi Madir,Amravti','Maharastra','444803','7058693391',4);
insert into TBL_ADDRESS (NAME,LANDMARK,STATE,ZIP_CODE,PHONE_NUMBER,USER_ID) VALUES('Mil Colony','Chilkhaldara','Maharastra','444800','3739093391',5);

INSERT INTO TBL_ORDER (QUANTITY,ADDRESS_ID,PRODUCT_ID,USER_ID) VALUES(10,1,1,1);
INSERT INTO TBL_ORDER (QUANTITY,ADDRESS_ID,PRODUCT_ID,USER_ID) VALUES(1,2,2,2);
INSERT INTO TBL_ORDER (QUANTITY,ADDRESS_ID,PRODUCT_ID,USER_ID) VALUES(2,1,1,1);
INSERT INTO TBL_ORDER (QUANTITY,ADDRESS_ID,PRODUCT_ID,USER_ID) VALUES(8,5,5,5);
INSERT INTO TBL_ORDER (QUANTITY,ADDRESS_ID,PRODUCT_ID,USER_ID) VALUES(1,4,4,4);